# Site settings
title: sudo code
email: gordon3.14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a journal of programming adventures
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  GordonGustafson

# Build settings
markdown: kramdown
exclude: ['Gemfile.lock', 'Gemfile']
